version: '3'
services:

  nginx-waf:
    image: alonnagar/gorilla:nginx-gorilla-waf
    ports:
      - "80:80"
    depends_on:
      - flask-waf
      - website

  flask-waf:
    image: alonnagar/gorilla:flask-gorilla-waf
    ports:
      - "3333:3333"
    depends_on:
      - mongo

  nginx-gui:
    image: alonnagar/gorilla:frontend-gorilla-gui
    ports:
      - "5555:80"
    depends_on:
      - flask-gui

  flask-gui:
    image: alonnagar/gorilla:backend-gorilla-gui
    ports:
      - "4444:4444"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  website:
    image: vulnerables/web-dvwa
    ports:
      - "7777:80"
