version: '3'
services:
  nginx:
    image: nginx-gorilla-waf
    ports:
      - "80:80"
    depends_on:
      - flask
      - website
  flask:
    image: flask-gorilla-waf
    ports:
      - "3333:3333"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  website:
    image: vulnerables/web-dvwa
    ports:
      - "7777:80"
